version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: skill-bdd
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql